// Curated list of widely-known disposable email domains. Not exhaustive —
// it's a low-effort signal, paired with rate limiting and other heuristics.
// Add entries as we observe abuse in production.

const DISPOSABLE_DOMAINS = new Set([
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "33mail.com",
  "anonbox.net",
  "anonymbox.com",
  "deadaddress.com",
  "discardmail.com",
  "dispostable.com",
  "easytrashmail.com",
  "fakeinbox.com",
  "getairmail.com",
  "getnada.com",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "harakirimail.com",
  "incognitomail.com",
  "instant-mail.de",
  "jetable.org",
  "kasmail.com",
  "mailcatch.com",
  "maildrop.cc",
  "mailinator.com",
  "mailinator.net",
  "mailmoat.com",
  "mailnesia.com",
  "mintemail.com",
  "moakt.com",
  "mohmal.com",
  "mt2015.com",
  "mytemp.email",
  "nada.email",
  "nada.ltd",
  "no-spam.ws",
  "nowmymail.com",
  "openmailbox.org",
  "owlpic.com",
  "pookmail.com",
  "rmqkr.net",
  "sharklasers.com",
  "sneakemail.com",
  "spam4.me",
  "spambog.com",
  "spamgourmet.com",
  "spammotel.com",
  "tempail.com",
  "tempinbox.com",
  "tempmail.com",
  "tempmail.us",
  "tempr.email",
  "throwawaymail.com",
  "trashmail.com",
  "trashmail.de",
  "trashmail.net",
  "trbvm.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
]);

export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf("@");
  if (at < 0) return false;
  const domain = email.slice(at + 1).toLowerCase().trim();
  return DISPOSABLE_DOMAINS.has(domain);
}
